function [ISI,AMP]=ESTIMcreateSUBfade(SUB,ISOFAST,PRECYCLE,MIDCYCLE,POSTCYCLE)
STARTDB=-60;

PRECLICK=PRECYCLE;
MIDCLICK=MIDCYCLE*SUB;
POSTCLICK=POSTCYCLE*SUB;
ISOSLOW=ISOFAST*SUB;

ISI=[ones(1,PRECLICK)*ISOSLOW,ones(1,MIDCLICK)*ISOFAST,ones(1,POSTCLICK)*ISOFAST];
temp=10.^(linspace(STARTDB/20, 0, MIDCLICK));
temp((SUB):SUB:end)=1;
AMP=[ones(1,PRECLICK),temp(1:MIDCLICK),ones(1,POSTCLICK)];

